"use client";

import { useEffect, useMemo, useRef } from "react";
import * as echarts from "echarts";
import { CandlestickSeries, ColorType, createChart, createSeriesMarkers, HistogramSeries, LineSeries } from "lightweight-charts";

export type MarketBar={time:number;open:number;high:number;low:number;close:number;volume:number};
type Trade=Record<string,any>;

function aggregate(bars:MarketBar[],minutes:number){
  if(minutes===1)return bars;
  const result:MarketBar[]=[];
  for(let i=0;i<bars.length;i+=minutes){const group=bars.slice(i,i+minutes);if(group.length!==minutes)continue;result.push({time:group[0].time,open:group[0].open,high:Math.max(...group.map(x=>x.high)),low:Math.min(...group.map(x=>x.low)),close:group.at(-1)!.close,volume:group.reduce((n,x)=>n+x.volume,0)})}
  return result;
}

export function TradingChart({bars,ema,trade,timeframe,showEma=true,indicatorLabel="EMA"}:{bars:MarketBar[];ema:{time:number;value:number}[];trade:Trade|null;timeframe:1|5;showEma?:boolean;indicatorLabel?:string}){
  const ref=useRef<HTMLDivElement>(null);
  const data=useMemo(()=>aggregate(bars,timeframe),[bars,timeframe]);
  useEffect(()=>{if(!ref.current||!data.length)return;const chart=createChart(ref.current,{height:560,layout:{background:{type:ColorType.Solid,color:"#0a0c10"},textColor:"#8d95a3",attributionLogo:true,fontFamily:"SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace"},grid:{vertLines:{color:"#161b24"},horzLines:{color:"#161b24"}},timeScale:{borderColor:"#232935",timeVisible:true,secondsVisible:false,rightOffset:5,barSpacing:timeframe===1?5:12},rightPriceScale:{borderColor:"#232935",scaleMargins:{top:.08,bottom:.18}},crosshair:{vertLine:{color:"#4d5563",labelBackgroundColor:"#2a313e"},horzLine:{color:"#4d5563",labelBackgroundColor:"#2a313e"}}});
    const candles=chart.addSeries(CandlestickSeries,{upColor:"#3ddc97",downColor:"#fb6b7c",wickUpColor:"#3ddc97",wickDownColor:"#fb6b7c",borderVisible:false});candles.setData(data as never);
    if(showEma&&ema.length){const line=chart.addSeries(LineSeries,{color:"#a08cff",lineWidth:2,priceLineVisible:false,lastValueVisible:true,title:indicatorLabel});line.setData(ema as never)}
    const volume=chart.addSeries(HistogramSeries,{priceFormat:{type:"volume"},priceScaleId:"",lastValueVisible:false,priceLineVisible:false});volume.priceScale().applyOptions({scaleMargins:{top:.88,bottom:0}});volume.setData(data.map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?"#1e5a41":"#5e2f38"})) as never);
    const markerTime=(stamp:string)=>{const target=Math.floor(new Date(stamp).getTime()/1000);return [...data].reverse().find(bar=>bar.time<=target)?.time??data[0].time};
    if(data[0])createSeriesMarkers(candles,[{time:data[0].time,position:"aboveBar",color:"#f2c15e",shape:"arrowDown",text:"09:30 OPEN"},...(trade?[{time:markerTime(trade.entry_ts),position:trade.side==="long"?"belowBar":"aboveBar",color:"#8ef0c5",shape:trade.side==="long"?"arrowUp":"arrowDown",text:`${trade.side.toUpperCase()} ENTRY`},{time:markerTime(trade.exit_ts),position:trade.side==="long"?"aboveBar":"belowBar",color:trade.net_pnl>=0?"#8ef0c5":"#ffa6b0",shape:"circle",text:`EXIT ${trade.net_pnl>=0?"+":""}$${Number(trade.net_pnl).toFixed(0)}`}]:[]) ] as never);
    if(trade){candles.createPriceLine({price:Number(trade.entry),color:"#e9ecf1",lineWidth:1,lineStyle:2,axisLabelVisible:true,title:"ENTRY"});candles.createPriceLine({price:Number(trade.target),color:"#3ddc97",lineWidth:2,lineStyle:2,axisLabelVisible:true,title:"4R TARGET"});candles.createPriceLine({price:Number(trade.stop),color:"#fb6b7c",lineWidth:2,lineStyle:2,axisLabelVisible:true,title:"STOP"})}
    chart.timeScale().fitContent();const resize=()=>chart.applyOptions({width:ref.current?.clientWidth});addEventListener("resize",resize);return()=>{removeEventListener("resize",resize);chart.remove()}},[data,ema,trade,timeframe,showEma,indicatorLabel]);
  const bounds=useMemo(()=>{if(!trade||!bars.length)return null;const hi=Math.max(...bars.map(x=>x.high),Number(trade.target));const lo=Math.min(...bars.map(x=>x.low),Number(trade.stop));const y=(price:number)=>8+(hi-price)/(hi-lo)*74;const entry=y(Number(trade.entry)),target=y(Number(trade.target)),stop=y(Number(trade.stop));return {targetTop:Math.min(entry,target),targetHeight:Math.max(1,Math.abs(target-entry)),stopTop:Math.min(entry,stop),stopHeight:Math.max(1,Math.abs(stop-entry))}},[trade,bars]);
  return <div className="chartStage"><div ref={ref} className="tradeChart" aria-label={`${timeframe}-minute candlestick chart with trade overlays`}/>{bounds&&<><div className="positionBox targetBox" style={{top:`${bounds.targetTop}%`,height:`${bounds.targetHeight}%`}}><span>PROFIT TARGET · +4R</span></div><div className="positionBox stopBox" style={{top:`${bounds.stopTop}%`,height:`${bounds.stopHeight}%`}}><span>STOP LOSS · −1R</span></div></>}</div>;
}

export function EquityChart({series}:{series:{name:string;color:string;data:number[]}[]}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);const longest=Math.max(0,...series.map(x=>x.data.length));chart.setOption({animationDuration:500,backgroundColor:"transparent",grid:{left:70,right:24,top:30,bottom:32},tooltip:{trigger:"axis",backgroundColor:"#12161e",borderColor:"#2a313e",borderWidth:1,padding:[8,12],textStyle:{color:"#e9ecf1",fontSize:12}},legend:{top:0,right:10,itemWidth:14,itemHeight:2,itemGap:18,textStyle:{color:"#8d95a3",fontSize:11}},xAxis:{type:"category",data:Array.from({length:longest},(_,i)=>i),axisLabel:{show:false},axisTick:{show:false},axisLine:{lineStyle:{color:"#232935"}}},yAxis:{type:"value",axisLabel:{color:"#727b8a",fontSize:11,formatter:(v:number)=>`$${Math.round(v/1000)}k`},splitLine:{lineStyle:{color:"#171c25"}}},series:series.map(item=>({name:item.name,type:"line",data:item.data,smooth:.12,showSymbol:false,lineStyle:{color:item.color,width:2},areaStyle:item===series[0]?{color:"rgba(61,220,151,.07)"}:undefined}))});const resize=()=>chart.resize();addEventListener("resize",resize);return()=>{removeEventListener("resize",resize);chart.dispose()}},[series]);return <div ref={ref} className="equityChart" aria-label="Net equity curve comparison"/>}

export function YearChart({values}:{values:Record<string,number>}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);const years=Object.keys(values),data=years.map(year=>values[year]);chart.setOption({grid:{left:62,right:18,top:20,bottom:32},tooltip:{trigger:"axis",backgroundColor:"#12161e",borderColor:"#2a313e",borderWidth:1,padding:[8,12],textStyle:{color:"#e9ecf1",fontSize:12},valueFormatter:(value:number)=>`$${value.toLocaleString()}`},xAxis:{type:"category",data:years,axisLabel:{color:"#8d95a3",fontSize:11},axisTick:{show:false},axisLine:{lineStyle:{color:"#232935"}}},yAxis:{type:"value",axisLabel:{color:"#727b8a",fontSize:11,formatter:(v:number)=>`$${Math.round(v/1000)}k`},splitLine:{lineStyle:{color:"#171c25"}}},series:[{type:"bar",data:data.map(value=>({value,itemStyle:{color:value>=0?"#3ddc97":"#fb6b7c",borderRadius:value>=0?[4,4,0,0]:[0,0,4,4]}})),barWidth:"52%"}]});const resize=()=>chart.resize();addEventListener("resize",resize);return()=>{removeEventListener("resize",resize);chart.dispose()}},[values]);return <div ref={ref} className="yearChart" aria-label="Year by year net profit"/>}
