"use client";

import { useEffect, useRef } from "react";
import * as echarts from "echarts";
import { CandlestickSeries, ColorType, createChart, HistogramSeries, LineSeries } from "lightweight-charts";
import { candles, equitySeries, type Candle } from "../lib/demo";
import { useLab } from "../store";

export function EquityChart({mode="equity"}:{mode?:"equity"|"drawdown"}){
  const ref=useRef<HTMLDivElement>(null);
  const overview=useLab(s=>s.overview);
  useEffect(()=>{if(!ref.current)return; const chart=echarts.init(ref.current);const yearly=(id:string)=>{const p=overview?.strategies?.[id]?.metrics?.by_year;if(!p)return null;let value=100;return Array.from({length:8},(_,i)=>{value+=(p[String(2018+i)]??0)/1000;return +value.toFixed(2)})}; const actualA=yearly("NQ:A1_4R"),actualB=yearly("NQ:B1_4R"),actualC=yearly("NQ:C5_sequential");const source=overview&&actualA&&actualB&&actualC?{a:actualA,b:actualB,c:actualC}:mode==="equity"?equitySeries:{a:[0,-2,-4,-1,-6,-3,-8,-2],b:[0,-4,-1,-6,-2,-8,-3,-9],c:[0,-1,-3,-1,-4,-2,-5,-1]};const axis=overview?Array.from({length:8},(_,i)=>2018+i):Array.from({length:source.a.length},(_,i)=>2018+i/2); chart.setOption({animationDuration:600,backgroundColor:"transparent",grid:{left:48,right:18,top:20,bottom:28},tooltip:{trigger:"axis",backgroundColor:"#10161e",borderColor:"#2b3542",textStyle:{color:"#dbe4ee",fontSize:11}},xAxis:{type:"category",data:axis,axisLine:{lineStyle:{color:"#26303b"}},axisLabel:{color:"#647181",fontSize:9,formatter:(v:number)=>Number.isInteger(+v)?v:""}},yAxis:{type:"value",axisLabel:{color:"#647181",fontSize:9,formatter:(v:number)=>mode==="equity"?`$${v}k`:`${v}%`},splitLine:{lineStyle:{color:"#161d26"}}},series:[{name:"A · 10:00",type:"line",data:source.a,smooth:.18,showSymbol:false,lineStyle:{color:"#4bd5e7",width:1.5}},{name:"B · 5m + EMA",type:"line",data:source.b,smooth:.18,showSymbol:false,lineStyle:{color:"#9d89ff",width:1.5}},{name:"Combined",type:"line",data:source.c,smooth:.18,showSymbol:false,lineStyle:{color:"#55dda0",width:2},areaStyle:{color:{type:"linear",x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:"#55dda022"},{offset:1,color:"#55dda000"}]},origin:"start"},markArea:{silent:true,itemStyle:{color:"#ffffff05"},label:{color:"#677383",fontSize:8},data:[[{name:"BLIND TEST",xAxis:2024},{xAxis:2025}]]}}]}); const resize=()=>chart.resize();addEventListener("resize",resize);return()=>{removeEventListener("resize",resize);chart.dispose()}},[mode,overview]);
  return <div ref={ref} className="echart" aria-label={`${mode} comparison chart`}/>;
}

export function Heatmap(){
  const ref=useRef<HTMLDivElement>(null);
  const overview=useLab(s=>s.overview);
  useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);const value=(id:string)=>overview?.strategies?.[id]?.metrics?.expectancy_r;const actual=[[0,0,value("NQ:B1_2R")],[1,0,value("NQ:B1_3R")],[2,0,value("NQ:B1_4R")],[2,1,value("NQ:B1_4R_cost2x")],[2,2,value("NQ:B1_4R_cost4x")],[2,3,value("MNQ:B1_4R")]].filter(x=>typeof x[2]==="number") as number[][];const vals=actual.length?actual:Array.from({length:12},(_,i)=>[i%3,Math.floor(i/3),.08+((i*17)%19)/100]);chart.setOption({grid:{left:96,right:8,top:12,bottom:28},tooltip:{formatter:(p:{value:number[]})=>`Expectancy: ${p.value[2].toFixed(3)}R`},xAxis:{type:"category",data:["2R","3R","4R"],axisLabel:{color:"#687586",fontSize:9},axisLine:{lineStyle:{color:"#26303b"}}},yAxis:{type:"category",data:["NQ baseline","NQ 2× costs","NQ 4× costs","MNQ replication"],axisLabel:{color:"#687586",fontSize:9},axisLine:{lineStyle:{color:"#26303b"}}},visualMap:{show:false,min:-.08,max:.14,inRange:{color:["#713441","#171d28","#245765","#54dba0"]}},series:[{type:"heatmap",data:vals,label:{show:true,color:"#d7e5e9",fontSize:8,formatter:(p:{value:number[]})=>p.value[2].toFixed(3)}}]});return()=>chart.dispose()},[overview]);return <div ref={ref} className="heatmap"/>;
}

export function ReplayChart({visible=210,data}:{visible?:number;data?:Candle[]}){
  const ref=useRef<HTMLDivElement>(null);const series=data?.length?data:candles();
  useEffect(()=>{if(!ref.current||!series.length)return;const chart=createChart(ref.current,{height:410,layout:{background:{type:ColorType.Solid,color:"#0a0f15"},textColor:"#748293",attributionLogo:true},grid:{vertLines:{color:"#151c24"},horzLines:{color:"#151c24"}},timeScale:{borderColor:"#28323e",timeVisible:true,secondsVisible:false},rightPriceScale:{borderColor:"#28323e"},crosshair:{vertLine:{color:"#465361",labelBackgroundColor:"#27313b"},horzLine:{color:"#465361",labelBackgroundColor:"#27313b"}}});const candle=chart.addSeries(CandlestickSeries,{upColor:"#56dca1",downColor:"#f36f7f",wickUpColor:"#56dca1",wickDownColor:"#f36f7f",borderVisible:false});candle.setData(series.slice(0,visible) as never);const ema=chart.addSeries(LineSeries,{color:"#9d89ff",lineWidth:1,priceLineVisible:false,lastValueVisible:false});let e=series[0].close;ema.setData(series.slice(0,visible).map(x=>{e=e+(x.close-e)*2/13;return {time:x.time,value:e}}) as never);const vol=chart.addSeries(HistogramSeries,{priceFormat:{type:"volume"},priceScaleId:"",color:"#253b43"});vol.priceScale().applyOptions({scaleMargins:{top:.86,bottom:0}});vol.setData(series.slice(0,visible).map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?"#245d4a":"#63343c"})) as never);const ten=series[30]?.open; if(ten)candle.createPriceLine({price:ten,color:"#4bd5e7",lineWidth:1,lineStyle:2,axisLabelVisible:true,title:"10:00 OPEN"});chart.timeScale().fitContent();const resize=()=>chart.applyOptions({width:ref.current?.clientWidth});addEventListener("resize",resize);return()=>{removeEventListener("resize",resize);chart.remove()}},[visible,data]);return <div ref={ref} className="replayChart"/>;
}
