"use client";

import { useCallback, useEffect, useState } from "react";

const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(value||0);
const iso=(value:string)=>value?new Date(value).toISOString():"";

export function PaperJournal({api}:{api:string}){
  const [status,setStatus]=useState<any>(null),[events,setEvents]=useState<any[]>([]),[error,setError]=useState("");
  const [activation,setActivation]=useState(""),[eventType,setEventType]=useState("eligible_session"),[sessionTs,setSessionTs]=useState("");
  const [form,setForm]=useState<Record<string,string>>({intended_entry_ts:"",available_market_price:"",spread_estimate_points:"0.25",simulated_fill:"",stop_price:"",exit_ts:"",exit_price:"",net_pnl:"",status:"completed",notes:""});
  const refresh=useCallback(()=>Promise.all([fetch(`${api}/api/paper/status`).then(r=>r.json()),fetch(`${api}/api/paper/events?limit=30`).then(r=>r.json())]).then(([next,log])=>{setStatus(next);setEvents(log.events??[])}).catch(reason=>setError(reason.message)),[api]);
  useEffect(()=>{refresh()},[refresh]);
  const activate=async()=>{setError("");try{const response=await fetch(`${api}/api/paper/activate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({activated_at:iso(activation),exit_method:"stop_and_1555"})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail??"Activation failed");setStatus(payload);await refresh()}catch(reason:any){setError(reason.message)}};
  const append=async()=>{setError("");try{const sessionDate=sessionTs?new Date(sessionTs).toISOString().slice(0,10):"";let payload:any;if(eventType==="eligible_session")payload={session_date:sessionDate,intended_entry_ts:form.intended_entry_ts,available_market_price:Number(form.available_market_price),spread_estimate_points:Number(form.spread_estimate_points),simulated_fill:Number(form.simulated_fill),stop_price:Number(form.stop_price),exit_ts:form.exit_ts,exit_price:Number(form.exit_price),net_pnl:Number(form.net_pnl),status:form.status,manual_deviation:form.notes||"none"};else if(eventType==="data_outage"||eventType==="manual_deviation")payload={session_date:sessionDate,description:form.notes};else payload={session_date:sessionDate,intended_entry_ts:form.intended_entry_ts,reason:form.notes};const response=await fetch(`${api}/api/paper/events`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_type:eventType,session_ts:iso(sessionTs),payload})});const body=await response.json();if(!response.ok)throw new Error(body.detail??"Journal append failed");await refresh()}catch(reason:any){setError(reason.message)}};
  if(!status)return <section className="paperPanel panel"><p>Loading the separate prospective journal…</p></section>;
  const active=status.configuration;
  return <section className="paperPanel panel">
    <div className="paperHead"><div><span>FORWARD-ONLY MODE</span><h2>Prospective paper journal</h2><p>Option C only: opening-candle direction, original stop, no target, close of the 15:55 bar. No broker connection.</p></div><div className="evidenceLabels"><b>Historical exploratory</b><b className="active">Prospective paper</b><b>Untouched holdout</b><b className="disabled">Live execution disabled</b></div></div>
    {!active?<div className="activationBox"><div><strong>Choose a future activation timestamp</strong><p>After activation, the configuration is immutable. Earlier sessions can never count as prospective.</p></div><label><span>ACTIVATION · YOUR LOCAL TIME</span><input type="datetime-local" value={activation} onChange={event=>setActivation(event.target.value)}/></label><button disabled={!activation} onClick={activate}>ACTIVATE PAPER MODE</button></div>:<>
      <div className="paperStatus"><div><span>STATUS</span><strong>{status.status.toUpperCase()}</strong></div><div><span>ACTIVATES</span><strong>{new Date(active.activated_at).toLocaleString()}</strong></div><div><span>CONFIGURATION</span><strong>IMMUTABLE · {active.config_hash.slice(0,10)}</strong></div><div><span>PAPER NET ONLY</span><strong className={status.prospective_results.net_profit>=0?"profit":"loss"}>{money(status.prospective_results.net_profit)}</strong></div><div><span>COMPLETED</span><strong>{status.prospective_results.completed_sessions}</strong></div></div>
      <div className="journalGrid"><div className="journalComposer"><div className="composerHead"><strong>Append audit event</strong><small>Records cannot be edited or deleted</small></div><div className="formGrid"><label><span>EVENT</span><select value={eventType} onChange={event=>setEventType(event.target.value)}><option value="eligible_session">Eligible completed session</option><option value="missed_signal">Missed signal</option><option value="rejected_signal">Rejected signal</option><option value="data_outage">Data outage</option><option value="manual_deviation">Manual deviation</option></select></label><label><span>SESSION TIMESTAMP</span><input type="datetime-local" value={sessionTs} onChange={event=>setSessionTs(event.target.value)}/></label><label><span>INTENDED 09:35 ENTRY</span><input value={form.intended_entry_ts} onChange={event=>setForm({...form,intended_entry_ts:event.target.value})} placeholder="ISO timestamp or 09:35 NY"/></label>{eventType==="eligible_session"&&<><Field label="AVAILABLE PRICE" name="available_market_price" form={form} setForm={setForm}/><Field label="SPREAD · POINTS" name="spread_estimate_points" form={form} setForm={setForm}/><Field label="SIMULATED FILL" name="simulated_fill" form={form} setForm={setForm}/><Field label="STOP" name="stop_price" form={form} setForm={setForm}/><label><span>EXIT TIMESTAMP</span><input value={form.exit_ts} onChange={event=>setForm({...form,exit_ts:event.target.value})} placeholder="ISO timestamp"/></label><Field label="EXIT PRICE" name="exit_price" form={form} setForm={setForm}/><Field label="NET PAPER P&L" name="net_pnl" form={form} setForm={setForm}/></>}<label className="notes"><span>{eventType==="eligible_session"?"MANUAL DEVIATION / NOTES":"REASON / DESCRIPTION"}</span><input value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label></div><button className="appendButton" disabled={!sessionTs} onClick={append}>APPEND TO AUDIT LOG</button></div>
      <div className="auditLog"><div className="composerHead"><strong>Append-only log</strong><small>{events.length} recent events</small></div>{events.map(row=><article key={row.event_uuid}><time>{new Date(row.recorded_at).toLocaleString()}</time><b>{row.event_type.replaceAll("_"," ")}</b><p>{row.payload.session_date??"Configuration activation"}{row.payload.net_pnl!==undefined?` · ${money(row.payload.net_pnl)}`:""}</p></article>)}</div></div>
    </>}
    {error&&<p className="paperError">{error}</p>}
    <div className="separationNote"><strong>SEPARATION GUARANTEE</strong><span>Historical results are never merged into this journal.</span><span>No live or automated order execution exists.</span></div>
  </section>;
}

function Field({label,name,form,setForm}:{label:string;name:string;form:Record<string,string>;setForm:(next:Record<string,string>)=>void}){return <label><span>{label}</span><input type="number" step="0.01" value={form[name]} onChange={event=>setForm({...form,[name]:event.target.value})}/></label>}
