"use client";

import { useCallback, useEffect, useState } from "react";
import { EquityChart, TradingChart, type MarketBar, YearChart } from "./components/Charts";
import { PaperJournal } from "./components/PaperJournal";

const API="http://127.0.0.1:8000";
const OPTIONS=[
  ["NQ:B_CANDLE_4R_fixed1","09:30 · First candle only · 4R · 1 NQ"],
  ["NQ:B_EMA_FULL_4R_fixed1","09:30 · Full overnight EMA · 4R · 1 NQ"],
  ["MNQ:B_CANDLE_4R_fixed1","09:30 · First candle only · 4R · 1 MNQ"],
  ["MNQ:B_EMA_FULL_4R_fixed1","09:30 · Full overnight EMA · 4R · 1 MNQ"],
  ["NQ:B_EMA_FULL_4R_risk1","09:30 · Full overnight EMA · 4R · 1% risk"],
  ["MNQ:B_EMA_FULL_4R_risk1","09:30 · Full overnight EMA · 4R · 1% MNQ"],
  ["NQ:B_ALWAYS_LONG_4R_fixed1","Control · Always long · 4R"],
  ["NQ:B_ALWAYS_SHORT_4R_fixed1","Control · Always short · 4R"],
  ["NQ:B_RANDOM_4R_fixed1","Control · Seeded random · 4R"],
  ["NQ:B_OVERNIGHT_4R_fixed1","Control · Overnight direction · 4R"],
  ["NQ:B_EMA_SAME_DAY_4R_fixed1","Control · Same-day EMA · 4R"],
  ["NQ:B_EMA_RTH_4R_fixed1","Control · Regular-session EMA · 4R"],
  ["NQ:A1_CONFIRMED_4R_risk1","10:00 · Confirmed structural pivot · 4R"],
  ["NQ:A1_CONFIRMED_2R_risk1","10:00 · Confirmed structural pivot · 2R"],
] as const;

const LABELS=Object.fromEntries(OPTIONS);
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0);
const pct=(value:number)=>`${value>=0?"+":""}${(value*100).toFixed(1)}%`;
const num=(value:number,digits=1)=>Number(value||0).toFixed(digits);

export default function Home(){
  const [overview,setOverview]=useState<any>(null),[opening,setOpening]=useState<any>(null),[phase4,setPhase4]=useState<any>(null),[phase5,setPhase5]=useState<any>(null),[phase7,setPhase7]=useState<any>(null),[error,setError]=useState("");
  const [variant,setVariant]=useState<string>(OPTIONS[0][0]),[timeframe,setTimeframe]=useState<1|5>(1),[advanced,setAdvanced]=useState(false);
  const [comparisonInstrument,setComparisonInstrument]=useState<"NQ"|"MNQ">("NQ"),[showEma,setShowEma]=useState(true);
  const [trades,setTrades]=useState<any[]>([]),[trade,setTrade]=useState<any|null>(null),[session,setSession]=useState<{bars:MarketBar[];ema:{time:number;value:number}[]}|null>(null);
  const [account,setAccount]=useState(100000),[risk,setRisk]=useState(1);
  useEffect(()=>{Promise.all([fetch(`${API}/api/research/overview`),fetch(`${API}/api/research/opening`),fetch(`${API}/api/research/phase4`),fetch(`${API}/api/research/phase5`),fetch(`${API}/api/research/phase7/summary`)]).then(async responses=>{if(responses.some(response=>!response.ok))throw new Error("Research API unavailable");const [base,open,audit,tournament,patterns]=await Promise.all(responses.map(response=>response.json()));setOverview(base);setOpening(open);setPhase4(audit);setPhase5(tournament);setPhase7(patterns)}).catch(reason=>setError(reason.message))},[]);
  const loadTrade=useCallback((selected:any)=>{setTrade(selected);const day=String(selected.entry_ts).slice(0,10);fetch(`${API}/api/research/session/${day}?symbol=${selected.instrument}`).then(response=>response.json()).then(payload=>setSession({bars:payload.bars??[],ema:payload.ema??[]})).catch(()=>setSession(null))},[]);
  useEffect(()=>{setTrades([]);setTrade(null);setSession(null);fetch(`${API}/api/research/trades?variant=${encodeURIComponent(variant)}&limit=160`).then(response=>response.json()).then(payload=>{const rows=payload.trades??[];setTrades(rows);if(rows[0])loadTrade(rows[0])}).catch(()=>{})},[variant,loadTrade]);
  if(!overview||!opening||!phase4||!phase5||!phase7)return <Loading error={error}/>;
  const current=overview.strategies[variant]??overview.strategies[OPTIONS[0][0]],metrics=current.metrics;
  const candle=overview.strategies["NQ:B_CANDLE_4R_fixed1"],full=overview.strategies["NQ:B_EMA_FULL_4R_fixed1"];
  const heroCandle=overview.strategies[`${comparisonInstrument}:B_CANDLE_4R_fixed1`],heroEma=overview.strategies[`${comparisonInstrument}:B_EMA_FULL_4R_fixed1`];
  const heroCandleResearch=opening.instrument_summary[comparisonInstrument].first_candle_only_fixed_one_contract;
  const heroEmaResearch=opening.instrument_summary[comparisonInstrument].full_overnight_ema_fixed_one_contract;
  const emaP=opening.statistical_benchmarks.ema_vs_simple.pvalues.consistent;
  const simpleP=opening.statistical_benchmarks.simple_vs_zero.pvalues.consistent;
  const evidence=current.evidence==="rejected"?{tone:"bad",title:"Rejected",text:"This rule lost in both validation and the later historical evaluation."}:current.evidence==="promising_exploratory"?{tone:"warn",title:"Promising, not proven",text:"Returns are positive, but the evidence is exploratory and no untouched holdout has been tested."}:{tone:"neutral",title:"Inconclusive",text:"The available periods do not support a stable positive or negative conclusion."};
  const compareKeys=["NQ:B_CANDLE_4R_fixed1","NQ:B_EMA_FULL_4R_fixed1","NQ:B_ALWAYS_LONG_4R_fixed1","NQ:B_ALWAYS_SHORT_4R_fixed1","NQ:B_RANDOM_4R_fixed1","NQ:B_OVERNIGHT_4R_fixed1","NQ:B_EMA_SAME_DAY_4R_fixed1","NQ:B_EMA_RTH_4R_fixed1"];
  const selectVariant=(next:string)=>{setVariant(next);if(next.startsWith("MNQ:"))setComparisonInstrument("MNQ");else if(next.startsWith("NQ:"))setComparisonInstrument("NQ")};
  const exitAudits=[['fixed_4r','A','Fixed 4R'],['fixed_5r','B','Fixed 5R'],['stop_and_1555','C','Stop + 15:55']] as const;
  return <main className="appShell">
    <header className="appHeader"><div className="identity"><span className="logo">O/T</span><div><strong>OPEN / TEN</strong><small>Nasdaq futures strategy tester</small></div></div><div className="headerStatus"><span className="liveDot"/>CORRECTED CACHE · 2018–2025 <b>2026 LOCKED</b></div><label className="researchSwitch"><input type="checkbox" checked={advanced} onChange={event=>setAdvanced(event.target.checked)}/><span/>Research details</label></header>

    <div className="page">
      <PatternLaboratory data={phase7}/>
      <div className="sectionLabel legacyLabel">PRESERVED EARLIER RESEARCH · INVALIDATED OR SUPERSEDED WHERE MARKED</div>
      <Phase5Tournament data={phase5} advanced={advanced}/>
      <div className="sectionLabel legacyLabel">PREVIOUS BOUNDED EXIT AUDIT · RETAINED FOR TRACEABILITY</div>
      <section className="controlBar legacyControls" aria-label="Previous-phase backtest controls">
        <label className="wideControl"><span>STRATEGY</span><select value={variant} onChange={event=>selectVariant(event.target.value)}>{OPTIONS.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>
        <label><span>ACCOUNT</span><select value={account} onChange={event=>setAccount(Number(event.target.value))}>{[25000,50000,100000,250000].map(value=><option value={value} key={value}>{money(value)}</option>)}</select></label>
        <label><span>RISK / TRADE</span><select value={risk} onChange={event=>setRisk(Number(event.target.value))}><option value={.25}>0.25%</option><option value={.5}>0.50%</option><option value={1}>1.00%</option></select></label>
        <div className="staticControl"><span>INSTRUMENT</span><strong>{variant.startsWith("MNQ")?"MNQ · $2 / point":"NQ · $20 / point"}</strong></div>
        <div className="staticControl"><span>PERIOD</span><strong>2018 — 2025</strong></div>
        <button className="cachedButton" title="This view changes between completed deterministic research runs">✓ CORRECTED RUN</button>
      </section>
      <section className="questionHero"><div><span>FINAL BOUNDED AUDIT</span><h1>Which transparent exit should go to prospective paper trading?</h1><p>Only 4R, 5R, and the original stop plus a fixed 15:55-bar-close exit were compared. Every result is historical exploratory evidence.</p></div><div className="instrumentToggle"><button className="active">NQ</button><button disabled>1 CONTRACT</button></div></section>
      <section className="phase4Decision"><div className="phase4Head"><div><span>PHASE 4 DECISION</span><h2>Recommend C · Stop plus 15:55 exit</h2><p>No target. The opposite-candle stop remains active from 09:35. This recommendation authorizes prospective paper trading only.</p></div><div className="choiceBadge"><strong>HISTORICAL EXPLORATORY</strong><small>Not validated · 2026 untouched</small></div></div><div className="exitAuditGrid">{exitAudits.map(([key,choice,title])=><ExitAuditCard key={key} choice={choice} title={title} item={phase4.variants[key]} selected={choice==="C"}/>)}</div><div className="boundedFacts"><div><span>WALK-FORWARD 2022–2025</span><strong>C SELECTED 4 OF 4 YEARS</strong><p>{money(phase4.walk_forward.combined_selected.net_profit)} combined; every forward year was positive. All years have now been inspected.</p></div><div><span>CAUSAL ENTRY DELAY</span><strong>09:36 {money(phase4.delayed_entry.delay_1m.delayed.net_profit)}</strong><p>{num(phase4.delayed_entry.delay_1m.delayed.expectancy_r,3)}R on {phase4.delayed_entry.delay_1m.matched_sessions.toLocaleString()} matched sessions. 09:37: {num(phase4.delayed_entry.delay_2m.delayed.expectancy_r,3)}R.</p></div><div><span>UPPER-TAIL WARNING</span><strong>{(phase4.variants.stop_and_1555.concentration.tests.best_5_trades.share_of_final_net_profit*100).toFixed(1)}% FROM BEST FIVE</strong><p>More single-trade concentration than 4R or 5R; this is the main prospective risk to audit.</p></div><div><span>ESTABLISHED SPA</span><strong>EXIT FAMILY p {phase4.statistical_reporting.exit_family_vs_fixed_4r.pvalues.consistent.display}</strong><p>1,474 observations · 50,000 resamples · block 10 · seed 4402. Not resolved at 5%.</p></div></div></section>

      <PaperJournal api={API}/>

      <div className="sectionLabel">EARLIER DIRECTION AUDIT · EMA REMAINS OPTIONAL</div>
      <section className="duelGrid">
        <ComparisonCard title="First Candle Only" subtitle="Trade in the 09:30–09:34 candle’s body direction" accent="simple" metrics={heroCandleResearch} core={heroCandle.metrics} selected={variant===`${comparisonInstrument}:B_CANDLE_4R_fixed1`} onSelect={()=>selectVariant(`${comparisonInstrument}:B_CANDLE_4R_fixed1`)} costLevels={comparisonInstrument==="NQ"?opening.pure_execution_cost_stress.first_candle_only.levels:[]}/>
        <ComparisonCard title="First Candle + EMA" subtitle="Direction from close relative to the full-overnight 12 EMA" accent="ema" metrics={heroEmaResearch} core={heroEma.metrics} selected={variant===`${comparisonInstrument}:B_EMA_FULL_4R_fixed1`} onSelect={()=>selectVariant(`${comparisonInstrument}:B_EMA_FULL_4R_fixed1`)} costLevels={comparisonInstrument==="NQ"?opening.pure_execution_cost_stress.full_overnight_ema.levels:[]}/>
      </section>
      <section className="differenceBand"><div><span>HISTORICAL DIFFERENCE · FIXED 1 CONTRACT</span><strong>{comparisonInstrument} EMA {heroEmaResearch.net_profit-heroCandleResearch.net_profit>=0?"+":""}{money(heroEmaResearch.net_profit-heroCandleResearch.net_profit)}</strong></div><div><span>ESTABLISHED NQ SPA TEST</span><strong className="notConvincing">p = {emaP.toFixed(3)} · NOT CONVINCING</strong></div><p>Both versions were historically profitable. The EMA version performed better in this sample, but the improvement is not strong enough to conclude that the EMA is responsible.</p></section>

      <section className={`verdict ${evidence.tone}`}><div className="verdictIcon">{evidence.tone==="bad"?"×":"!"}</div><div><span>SELECTED RUN</span><strong>{evidence.title}</strong><p>{evidence.text}</p></div><div className="verdictFact"><span>SIMPLE RULE VS ZERO</span><b>{simpleP<.05?"STATISTICALLY RESOLVED":"HISTORICALLY POSITIVE"}</b><small>Established SPA p {simpleP.toFixed(3)}</small></div><div className="verdictFact"><span>2026 HOLDOUT</span><b>UNTOUCHED</b><small>No candidate frozen</small></div></section>

      <section className="kpis"><Kpi label="NET PROFIT" value={money(metrics.net_profit)} note={`${pct(metrics.total_return)} on selected sizing`} positive={metrics.net_profit>0}/><Kpi label="MAX DRAWDOWN" value={pct(metrics.max_drawdown)} note={`${metrics.drawdown_duration_trades} trades underwater`} bad/><Kpi label="WIN RATE" value={`${(metrics.win_rate*100).toFixed(1)}%`} note={`${metrics.trades.toLocaleString()} completed trades`}/><Kpi label="PROFIT FACTOR" value={num(metrics.profit_factor,2)} note={`${money(metrics.reference_gross_pnl)} reference gross`}/><Kpi label="AVG. TRADE" value={money(metrics.expectancy)} note={`${num(metrics.expectancy_r,3)}R after costs`} positive={metrics.expectancy>0}/><Kpi label="TOTAL COSTS" value={money(metrics.total_costs)} note={`${money(metrics.spread_cost)} spread · ${money(metrics.slippage)} slip`}/></section>

      <section className="terminal panel">
        <div className="panelTitle chartTitle"><div><span>TRADE REPLAY</span><h2>{trade?`${trade.instrument} · ${String(trade.entry_ts).slice(0,10)}`:"Select a completed trade"}</h2></div><div className="chartLegend"><button className={showEma?"emaToggle active":"emaToggle"} onClick={()=>setShowEma(value=>!value)}><i className="emaKey"/>EMA {showEma?"ON":"OFF"}</button><i className="entryKey"/>Entry <i className="targetKey"/>Target <i className="stopKey"/>Stop</div><div className="timeframe"><button className={timeframe===1?"active":""} onClick={()=>setTimeframe(1)}>1 MIN</button><button className={timeframe===5?"active":""} onClick={()=>setTimeframe(5)}>5 MIN</button></div></div>
        <div className="terminalBody"><div className="chartColumn">{session?<TradingChart bars={session.bars} ema={session.ema} trade={trade} timeframe={timeframe} showEma={showEma}/>:<div className="chartEmpty">Choose a trade to load its cached market session.</div>}</div><aside className="tradeRail"><div className="tradeRailHead"><div><span>COMPLETED TRADES</span><b>{trades.length} recent</b></div><small>Click to jump to chart</small></div><div className="tradeRows">{trades.map(row=><button key={row.id} className={trade?.id===row.id?"selected":""} onClick={()=>loadTrade(row)}><time>{String(row.entry_ts).slice(0,10)}<small>{String(row.entry_ts).slice(11,16)} NY</small></time><span className={row.side}>{row.side.toUpperCase()}</span><strong className={row.net_pnl>=0?"profit":"loss"}>{row.net_pnl>=0?"+":""}{money(row.net_pnl)}<small>{num(row.realized_r,2)}R · {row.outcome}</small></strong></button>)}</div></aside></div>
        {trade&&<div className="fillAudit"><span>REFERENCE {Number(trade.reference_entry).toFixed(2)} → {Number(trade.reference_exit).toFixed(2)}</span><span>ACTUAL FILL {Number(trade.entry).toFixed(2)} → {Number(trade.exit).toFixed(2)}</span><span>GROSS {money(trade.gross_pnl)}</span><span className="cost">COSTS −{money(trade.total_costs)}</span><strong>NET {money(trade.net_pnl)}</strong></div>}
      </section>

      <section className="analysisGrid"><article className="panel"><div className="panelTitle"><div><span>PERFORMANCE</span><h2>Net equity curve</h2></div><small>Corrected gross-to-net accounting</small></div><EquityChart series={[{name:"Full overnight EMA",color:"#8f7dff",data:full.equity},{name:"First-candle control",color:"#4fd7a2",data:candle.equity}]}/></article><article className="panel"><div className="panelTitle"><div><span>CONSISTENCY</span><h2>Year-by-year net profit</h2></div><small>{metrics.positive_years} of {metrics.years_observed} positive years</small></div><YearChart values={metrics.by_year}/></article></section>

      <section className="panel comparePanel"><div className="panelTitle"><div><span>MATCHED CONTROLS</span><h2>Does the EMA direction actually help?</h2></div><p>Every row uses the same session selection, opposite-candle stop, 4R target, one contract, and realistic costs.</p></div><div className="compareTable"><div className="compareHead"><span>RULE</span><span>NET PROFIT</span><span>WIN RATE</span><span>PROFIT FACTOR</span><span>AVG. R</span><span>EVIDENCE</span></div>{compareKeys.map(key=>{const item=overview.strategies[key],m=item.metrics;return <button key={key} onClick={()=>selectVariant(key)} className={variant===key?"activeRow":""}><span><b>{LABELS[key]??key}</b><small>{key.replace("NQ:","")}</small></span><span className={m.net_profit>=0?"profit":"loss"}>{money(m.net_profit)}</span><span>{(m.win_rate*100).toFixed(1)}%</span><span>{num(m.profit_factor,2)}</span><span>{num(m.expectancy_r,3)}R</span><em className={item.evidence}>{item.evidence.replaceAll("_"," ")}</em></button>})}</div><div className="plainFinding"><b>Plain-language finding</b><p>The EMA version earned {money(full.metrics.net_profit-candle.metrics.net_profit)} more than first-candle direction over the full sample, but the session-matched uncertainty interval crosses zero. The improvement could be noise, so this is not evidence that the EMA adds value.</p></div></section>

      <section className="practicalGrid">
        <article className="panel insightCard"><span>RECOMMENDED EXIT · BREAK-EVEN COST</span><strong>{money(phase4.variants.stop_and_1555.cost_break_even.break_even_all_in_round_trip_cost)}</strong><p>per NQ round trip for option C, versus the $20.10 baseline. This is the largest cost buffer of the three bounded exits.</p></article>
        <article className="panel insightCard"><span>RANDOMLY MISS 20%</span><strong className="profit">{money(opening.missed_trade_scenarios.random[2].median_net_profit)}</strong><p>median remaining net profit; {pct(opening.missed_trade_scenarios.random[2].probability_profitable)} of simulations remained profitable.</p></article>
        <article className="panel insightCard caution"><span>ADVERSE-SELECTION STRESS · NOT NEUTRAL</span><strong className="loss">{money(opening.missed_trade_scenarios.entry_moved_away_before_manual_order.remaining.net_profit)}</strong><p>This deliberately excludes trades that immediately moved correctly and selects against continuation winners. It is not a neutral missed-trade simulation.</p></article>
        <article className="panel insightCard"><span>IS 4R SPECIAL?</span><strong>NO</strong><p>2.5R–5R were positive; 5R and fixed end-of-day exits earned more in-sample. All target work remains exploratory.</p></article>
      </section>

      <section className="splitGrid"><article className="panel splitPanel"><div className="panelTitle"><div><span>INDEPENDENT PERIODS</span><h2>No equity leaks between periods</h2></div></div>{Object.entries(current.periods).map(([name,value]:any)=><div className="splitRow" key={name}><span>{name.replaceAll("_"," ")}</span><b className={value.net_profit>=0?"profit":"loss"}>{money(value.net_profit)}</b><em>{value.trades} trades</em><small>{pct(value.total_return)} · {num(value.expectancy_r,3)}R</small></div>)}</article><article className="panel costPanel"><div className="panelTitle"><div><span>EXECUTION REALITY</span><h2>What the result pays for</h2></div></div><dl><div><dt>Reference gross P&L</dt><dd>{money(metrics.reference_gross_pnl)}</dd></div><div><dt>Bid/ask spread</dt><dd>−{money(metrics.spread_cost)}</dd></div><div><dt>Entry + exit slippage</dt><dd>−{money(metrics.slippage)}</dd></div><div><dt>Commission + exchange + clearing</dt><dd>−{money(metrics.fees)}</dd></div><div className="net"><dt>Net P&L</dt><dd>{money(metrics.net_profit)}</dd></div></dl><p>NQ assumes $5.10 round-trip fees per contract. MNQ assumes $2.40. Both apply one tick of slippage per side and one round-trip spread tick.</p></article></section>

      {advanced&&<section className="researchPanel panel"><div className="panelTitle"><div><span>ADVANCED RESEARCH</span><h2>Bounded Phase 4 audit details</h2></div><button onClick={()=>setAdvanced(false)}>Hide research details</button></div><div className="researchCards"><Research label="Fixed 4R vs zero" value={`p ${phase4.statistical_reporting.fixed_4r_vs_zero.pvalues.consistent.display}`} note="1,474 observations · seed 4401"/><Research label="Exit family vs 4R" value={`p ${phase4.statistical_reporting.exit_family_vs_fixed_4r.pvalues.consistent.display}`} note="4R benchmark · seed 4402"/><Research label="Random direction" value="OMITTED" note="One seeded random path is insufficient evidence"/><Research label="Monte Carlo resolution" value="≈ 0.00002" note="50,000 stationary resamples · block 10"/><Research label="C · best five / net" value={`${(phase4.variants.stop_and_1555.concentration.tests.best_5_trades.share_of_final_net_profit*100).toFixed(1)}%`} note={`${money(phase4.variants.stop_and_1555.concentration.tests.best_5_trades.remaining.net_profit)} remains`}/><Research label="Holding-time correction" value="24m median" note="89m mean for simple fixed 4R"/></div><p className="methodNote">Every bootstrap row specifies its benchmark, 1,474 observations, 50,000 resamples, expected block length 10, and seed. Lower, consistent, and upper SPA values are retained in the Phase 4 artifact. A zero exceedance would display as p ≤ approximately 0.00002, never p = 0.00000. All 2018–2025 observations have now been inspected, so none is a clean holdout.</p><div className="researchDetailGrid"><div><span>BOUNDED WALK-FORWARD</span><p>Only 4R, 5R, and stop-plus-15:55 were eligible. Prior cumulative after-cost profit selected option C before each test year from 2022 through 2025; combined forward net was {money(phase4.walk_forward.combined_selected.net_profit)}.</p></div><div><span>CONCENTRATION</span><p>Option C’s best trade contributed {(phase4.variants.stop_and_1555.concentration.tests.best_1_trades.share_of_final_net_profit*100).toFixed(1)}% of net and its best five contributed {(phase4.variants.stop_and_1555.concentration.tests.best_5_trades.share_of_final_net_profit*100).toFixed(1)}%. Removing the best 20 makes it negative.</p></div><div><span>CAUSAL DELAY</span><p>09:36 rejects {phase4.delayed_entry.delay_1m.rejections.stop_touched_before_entry} sessions whose stop was already touched, recalculates risk and target, and earns {num(phase4.delayed_entry.delay_1m.delayed.expectancy_r,3)}R. At 09:37, {phase4.delayed_entry.delay_2m.rejections.stop_touched_before_entry} are rejected and expectancy is {num(phase4.delayed_entry.delay_2m.delayed.expectancy_r,3)}R.</p></div></div></section>}

      <footer><span>5.84M licensed minute bars remain local and unchanged.</span><span>2018–2025 corrected research · America/New_York</span><strong>2026 NOT DOWNLOADED OR TESTED</strong></footer>
    </div>
  </main>;
}

type PatternView="overview"|"failures"|"winners"|"management"|"tournament"|"statistics"|"registry";
function PatternLaboratory({data}:{data:any}){
  const [view,setView]=useState<PatternView>("overview");
  const baseline=data.baseline??{},tail=data.tail??{},management=data.management??{},statistics=data.statistics??{};
  const tabs:[PatternView,string][]=[["overview","C01 overview"],["failures","Loss anatomy"],["winners","Winner anatomy"],["management","Early management"],["tournament","Tournament"],["statistics","Statistics"],["registry","Registry"]];
  const topLosses=(data.losses??[]).slice(0,10),topWinners=(data.winners??[]).slice(0,10);
  const comparison=statistics.paired_comparisons??{},reality=statistics.reality_check_spa?.["10"]??{};
  return <section className="patternLab" aria-label="Phase 7 Pattern Laboratory">
    <div className="patternHero"><div><span>PHASE 7 · PATTERN LABORATORY</span><h1>The strategy still makes money. Its rare winners remain the problem.</h1><p>{data.verdict}</p></div><div className="patternLock"><small>2026 MARKET HOLDOUT</small><strong>UNTOUCHED</strong><span>{data.registry?.consumed}/{data.registry?.maximum} experiments</span></div></div>
    <nav className="patternTabs" aria-label="Pattern Laboratory views">{tabs.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav>
    <div className="availabilityLegend"><span><i className="pre"/>PRE-ENTRY</span><span><i className="entry"/>ENTRY-TIME</span><span><i className="post"/>POST-ENTRY</span><span><i className="outcome"/>OUTCOME-ONLY</span><small>Every finding is labeled by when it was actually knowable.</small></div>
    {view==="overview"&&<><section className="patternKpis"><Kpi label="CORRECTED NET" value={money(baseline.net_profit)} note={`${Number(baseline.trades??0).toLocaleString()} causal trades`} positive/><Kpi label="PROFIT FACTOR" value={num(baseline.profit_factor,2)} note={`${Number((baseline.win_rate??0)*100).toFixed(1)}% win rate`}/><Kpi label="MAX DRAWDOWN" value={pct(baseline.max_drawdown??0)} note={`${baseline.positive_years}/8 positive years`} bad/><Kpi label="AFTER BEST TRADE" value={money(baseline.net_after_best_trade)} note="Still historically positive"/><Kpi label="AFTER BEST 1%" value={money(baseline.net_after_best_1pct)} note="Fails the tail gate" bad/><Kpi label="MEDIAN TRADE" value={money(baseline.median_trade)} note="Right-skewed payoff" bad/></section><div className="patternOverview"><article className="patternPanel"><div className="panelTitle"><div><span>CORRECTED CAUSAL EQUITY</span><h2>C01 after the Phase 5 timing repair</h2></div><small>Fixed 1 NQ · exact costs</small></div><EquityChart series={[{name:"Corrected C01",color:"#6ce5b1",data:baseline.equity??[]}]}/></article><article className="patternPanel tailPanel"><span>TAIL DEPENDENCE</span><h2>Headline return does not survive exceptional-day removal.</h2><dl><div><dt>Original</dt><dd>{money(tail.original_net)}</dd></div><div><dt>Best 5 removed</dt><dd>{money(tail.best_5_removed)}</dd></div><div><dt>Best 1% removed</dt><dd className="loss">{money(tail.best_1pct_removed)}</dd></div><div><dt>Best 5% removed</dt><dd className="loss">{money(tail.best_5pct_removed)}</dd></div></dl><p>This does not prove the edge is fake. It means missing a small number of unusually strong days can erase it.</p></article></div><div className="costCards">{["1","1.5","2","3","4"].map(level=><article key={level}><span>{level}× COSTS</span><strong className={(data.cost_stress?.[level]?.original_net??0)>=0?"profit":"loss"}>{money(data.cost_stress?.[level]?.exact_engine_net??data.cost_stress?.[level]?.original_net)}</strong><small>{money(data.cost_stress?.[level]?.best_1pct_removed)} after best 1%</small></article>)}</div></>}
    {view==="failures"&&<PatternRows title="Recurring failure mechanisms" intro="Overlapping labels describe failed follow-through; POST-ENTRY labels cannot be used to decide whether to enter." rows={topLosses} metric={(row:any)=>`${row.count.toLocaleString()} · ${num(row.mean_r,2)}R`} availability={(row:any)=>row.feature_availability}/>} 
    {view==="winners"&&<PatternRows title="Winner descriptions" intro="Lift is calculated against every eligible C01 trade. These remain descriptions until chronological prediction succeeds." rows={topWinners} metric={(row:any)=>`${row.lift_r>=0?"+":""}${num(row.lift_r,2)}R lift`} availability={(row:any)=>row.feature_availability}/>} 
    {view==="management"&&<div className="patternTable"><header><div><span>CAUSAL POST-ENTRY RULES</span><h2>Can we cut failures without deleting the rare winners?</h2></div><p>Best historical rule: <b>{String(management.best_rule??"").replaceAll("_"," ")}</b>. It remains exploratory.</p></header><div className="patternRows"><div className="patternRow head"><span>RULE</span><span>TRIGGERS</span><span>NET CHANGE</span><span>BEST 1% REMOVED</span><span>WINNERS CUT</span></div>{Object.entries(management.rules??{}).map(([name,row]:[string,any])=><div className="patternRow" key={name}><span><b>{name.replaceAll("_"," ")}</b><small>POST-ENTRY · {row.decision_minutes_after_entry} minutes</small></span><span>{row.triggers}</span><strong className={row.improvement>=0?"profit":"loss"}>{row.improvement>=0?"+":""}{money(row.improvement)}</strong><span className={row.tail?.best_1pct_removed>=0?"profit":"loss"}>{money(row.tail?.best_1pct_removed)}</span><span>{row.winners_prematurely_cut}</span></div>)}</div></div>}
    {view==="tournament"&&<div className="patternTable"><header><div><span>EQUAL-TREATMENT TOURNAMENT</span><h2>No strategy cleared every gate.</h2></div><p>{data.tournament?.reason}</p></header><div className="scorecards">{Object.entries(data.tournament?.scorecards??{}).map(([name,row]:[string,any])=><article key={name}><div><b>{name}</b><em>{row.causal_correctness}</em></div><strong>{money(row.expectancy)} / session</strong><dl><div><dt>Sessions</dt><dd>{row.sample_size}</dd></div><div><dt>Positive years</dt><dd>{row.year_stability}/8</dd></div><div><dt>Tail net</dt><dd className={row.tail_robustness>=0?"profit":"loss"}>{money(row.tail_robustness)}</dd></div><div><dt>Drawdown</dt><dd>{pct(row.drawdown??0)}</dd></div></dl></article>)}</div></div>}
    {view==="statistics"&&<div className="patternStats"><article><span>WHITE REALITY CHECK</span><strong>p {num(reality.reality_check_p_value,3)}</strong><p>Best family member versus the matched first-candle benchmark.</p></article><article><span>HANSEN SPA-STYLE</span><strong>p {num(reality.spa_p_value,3)}</strong><p>Studentized family maximum with stationary blocks.</p></article><article><span>DEFLATED SHARPE</span><strong>{num(statistics.deflated_sharpe?.dsr_probability,3)}</strong><p>{statistics.deflated_sharpe?.trials} declared trials.</p></article><article><span>CSCV / PBO</span><strong>{num(statistics.pbo?.pbo,3)}</strong><p>Historically inspected model-selection risk.</p></article><div className="statComparisons">{Object.entries(comparison).map(([name,row]:[string,any])=><div key={name}><span>{name.replaceAll("_"," ")}</span><b>p {num(row?.["10"]?.two_sided_p,3)}</b><small>BY {num(row?.["10"]?.by_adjusted_p,3)}</small></div>)}</div></div>}
    {view==="registry"&&<div className="registryView"><div><span>RESEARCH CONTRACT</span><h2>{data.contract_id}</h2><p>{data.data_boundary}. Every experiment references the contract and the runner stops at 150.</p></div><div className="budgetRing"><strong>{data.registry?.consumed}</strong><span>OF {data.registry?.maximum}</span><small>{data.registry?.remaining} deferred capacity</small></div><div><span>KNOWLEDGE GRAPH</span><h2>Obsidian-compatible research brain</h2><p>Strategies, mechanisms, failures, statistics, rejected hypotheses, execution risks, and decisions are linked from <code>{data.research_brain}</code>.</p></div></div>}
  </section>;
}

function PatternRows({title,intro,rows,metric,availability}:{title:string;intro:string;rows:any[];metric:(row:any)=>string;availability:(row:any)=>string}){return <div className="patternTable"><header><div><span>CAUSAL FORENSICS</span><h2>{title}</h2></div><p>{intro}</p></header><div className="patternRows"><div className="patternRow compact head"><span>MECHANISM</span><span>AVAILABILITY</span><span>SAMPLE / EFFECT</span><span>PROFIT FACTOR</span></div>{rows.map(row=><div className="patternRow compact" key={row.name}><span><b>{String(row.name).replaceAll("_"," ")}</b><small>{row.mechanically_defined?"Mechanical definition":"Descriptive"}</small></span><em className={String(availability(row)).toLowerCase().replace("_","-")}>{String(availability(row)).replace("_"," ")}</em><strong>{metric(row)}</strong><span>{num(row.profit_factor,2)}</span></div>)}</div></div>}

const PHASE5_NAMES:Record<string,string>={
  C01:"15-minute opening-range breakout + volume + EMA200",
  C02:"Opening-range breakout retest",
  C03:"Prior-day high / low sweep reversal",
  C04:"Overnight range breakout",
  C05:"Confirmed trend-pivot pullback",
  C08:"Gap continuation",
  C09:"Gap fade",
  C10:"VWAP continuation",
  C11:"Opening drive continuation",
  C14:"Inside-day breakout",
  C15:"Previous-close breakout",
  C16:"Opening-range mean reversion",
  C17:"Seeded negative control",
  BASE_CANDLE:"Matched control · first-candle direction",
  BASE_NONE:"Matched control · no trade",
  BASE_EMA:"Matched control · overnight EMA direction",
  BASE_LONG:"Matched control · always long",
  BASE_SHORT:"Matched control · always short",
  BASE_RANDOM:"Matched control · seeded random",
};

function Phase5Tournament({data,advanced}:{data:any;advanced:boolean}){
  const [candidate,setCandidate]=useState("C01"),[instrument,setInstrument]=useState<"NQ"|"MNQ">("NQ"),[exit,setExit]=useState<"matched_4R"|"matched_EOD">("matched_4R"),[sizing,setSizing]=useState<"fixed1"|"risk1">("fixed1"),[cost,setCost]=useState<1|2|4>(1);
  const [timeframe,setTimeframe]=useState<1|5>(1),[trades,setTrades]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[session,setSession]=useState<{bars:MarketBar[];ema:{time:number;value:number}[];indicatorLabel:string}|null>(null),[chartError,setChartError]=useState("");
  const runKey=`${instrument}:${candidate}:${exit}:${sizing}`;
  const summary=data.summaries?.[runKey]??data.summaries?.["NQ:C01:matched_4R:fixed1"]??{};
  const disposition=data.candidate_dispositions?.[candidate];
  const evidence=candidate==="C01"?"invalid_lookahead_historical_result":disposition?.evidence??(candidate.startsWith("BASE_")?"matched control":"descriptive");
  const net=summary.cost_stress_net?.[String(cost)]??summary.net_profit??0;
  const load=useCallback((row:any)=>{setSelected(row);setChartError("");const day=String(row.entry_ts).slice(0,10),indicator=candidate==="C01"?"c01_ema200":"none";fetch(`${API}/api/research/session/${day}?symbol=${row.instrument}&indicator=${indicator}`).then(response=>{if(!response.ok)throw new Error(`session API ${response.status}`);return response.json()}).then(payload=>setSession({bars:payload.bars??[],ema:payload.ema??[],indicatorLabel:payload.indicator_label??"Indicator"})).catch(reason=>{setSession(null);setChartError(String(reason?.message??reason))})},[candidate]);
  useEffect(()=>{setTrades([]);setSelected(null);setSession(null);setChartError("");fetch(`${API}/api/research/phase5/trades?run_key=${encodeURIComponent(runKey)}&limit=160`).then(response=>{if(!response.ok)throw new Error(`trade API ${response.status}`);return response.json()}).then(payload=>{const rows=payload.trades??[];setTrades(rows);if(rows[0])load(rows[0])}).catch(reason=>setChartError(String(reason?.message??reason)))},[runKey,load]);
  const candidateIds=Object.keys(data.candidate_dispositions??{}).filter(id=>data.summaries?.[`NQ:${id}:matched_4R:fixed1`]);
  const controls=["BASE_NONE","BASE_CANDLE","BASE_EMA","BASE_LONG","BASE_SHORT","BASE_RANDOM"].filter(id=>data.summaries?.[`NQ:${id}:matched_4R:fixed1`]);
  const compareIds=["C01",...candidateIds.filter(id=>id!=="C01")].slice(0,8);
  return <>
    <section className="tournamentHero invalidated">
      <div><span>PHASE 5 · PRESERVED INVALIDATED TOURNAMENT</span><h1>The original C01 headline used an incomplete 15-minute candle.</h1><p>This section remains visible for traceability. Its C01 result entered ten minutes too early and is labeled <b>INVALID LOOKAHEAD HISTORICAL RESULT</b>. Use the Phase 7 Pattern Laboratory above for corrected evidence.</p></div>
      <div className="tournamentSeal"><small>PHASE 5 C01</small><strong>INVALID</strong><span>{data.raw_cache_immutable?"ARTIFACT PRESERVED":"CHECK REQUIRED"}</span></div>
    </section>
    <section className="phase5Controls" aria-label="Phase 5 tournament controls">
      <label className="candidateControl"><span>STRATEGY / CONTROL</span><select value={candidate} onChange={event=>setCandidate(event.target.value)}><optgroup label="Tournament candidates">{candidateIds.map(id=><option key={id} value={id}>{id} · {PHASE5_NAMES[id]??id}</option>)}</optgroup><optgroup label="Matched controls">{controls.map(id=><option key={id} value={id}>{PHASE5_NAMES[id]??id}</option>)}</optgroup></select></label>
      <label><span>CONTRACT</span><select value={instrument} onChange={event=>setInstrument(event.target.value as "NQ"|"MNQ")}><option>NQ</option><option>MNQ</option></select></label>
      <label><span>EXIT</span><select value={exit} onChange={event=>setExit(event.target.value as "matched_4R"|"matched_EOD")}><option value="matched_4R">Matched 4R</option><option value="matched_EOD">15:55 close</option></select></label>
      <label><span>SIZING</span><select value={sizing} onChange={event=>setSizing(event.target.value as "fixed1"|"risk1")}><option value="fixed1">1 contract</option><option value="risk1">1% risk · capped</option></select></label>
      <label><span>COST STRESS</span><select value={cost} onChange={event=>setCost(Number(event.target.value) as 1|2|4)}><option value={1}>Baseline</option><option value={2}>2× costs</option><option value={4}>4× costs</option></select></label>
      <div className="phase5Static"><span>ACCOUNT BASIS</span><strong>$100,000 · independent periods</strong></div>
      <div className="phase5Static"><span>PERIOD</span><strong>2018–2025 · all inspected</strong></div>
    </section>
    <section className={`phase5Verdict ${evidence}`}><div><span>SELECTED EVIDENCE</span><strong>{String(evidence).replaceAll("_"," ")}</strong><p>{disposition?.reason??"Matched benchmark using identical sessions, exits, sizing, and costs."}</p></div><div><span>RUN KEY</span><code>{runKey}</code></div><div><span>ACCEPTED SESSIONS</span><strong>{Number(summary.accepted_sessions??0).toLocaleString()}</strong></div></section>
    <section className="kpis phase5Kpis"><Kpi label={candidate==="C01"?"INVALID LEGACY NET":`NET PROFIT · ${cost}× COST`} value={money(net)} note={candidate==="C01"?"Not evidence · incomplete-candle look-ahead":`${pct(net/100000)} on the run's independent $100k basis`} positive={candidate!=="C01"&&net>0}/><Kpi label="MAX DRAWDOWN" value={pct(summary.max_drawdown??0)} note={`${summary.drawdown_duration_trades??0} trades underwater`} bad/><Kpi label="WIN RATE" value={`${Number((summary.win_rate??0)*100).toFixed(1)}%`} note={`${Number(summary.trades??0).toLocaleString()} completed trades`}/><Kpi label="PROFIT FACTOR" value={num(summary.profit_factor??0,2)} note={`${num(summary.expectancy_session_r??0,3)}R per accepted session`}/><Kpi label="POSITIVE YEARS" value={`${summary.positive_years??0}/8`} note="Calendar-year concentration check"/><Kpi label="TOTAL BASE COSTS" value={money(summary.total_costs??0)} note="Spread + slippage + separate contract fees"/></section>
    <section className="phase5Workbench panel">
      <div className="panelTitle chartTitle"><div><span>REAL CACHED TRADE REPLAY</span><h2>{selected?`${PHASE5_NAMES[candidate]??candidate} · ${String(selected.entry_ts).slice(0,10)}`:"No completed trade for this run"}</h2></div><div className="timeframe"><button className={timeframe===1?"active":""} onClick={()=>setTimeframe(1)}>1 MIN</button><button className={timeframe===5?"active":""} onClick={()=>setTimeframe(5)}>5 MIN</button></div></div>
      <div className="terminalBody"><div className="chartColumn">{session?<TradingChart bars={session.bars} ema={session.ema} trade={selected} timeframe={timeframe} showEma={candidate==="C01"} indicatorLabel={session.indicatorLabel}/>:<div className="chartEmpty">{chartError?`Chart data error: ${chartError}`:"This selected run produced no cached trade to replay."}</div>}</div><aside className="tradeRail"><div className="tradeRailHead"><div><span>COMPLETED TRADES</span><b>{trades.length} recent</b></div><small>Click to inspect</small></div><div className="tradeRows">{trades.map(row=><button key={row.id} className={selected?.id===row.id?"selected":""} onClick={()=>load(row)}><time>{String(row.entry_ts).slice(0,10)}<small>{String(row.entry_ts).slice(11,16)} NY</small></time><span className={row.side}>{row.side.toUpperCase()}</span><strong className={row.net_pnl>=0?"profit":"loss"}>{row.net_pnl>=0?"+":""}{money(row.net_pnl)}<small>{num(row.realized_r,2)}R · {row.outcome}</small></strong></button>)}</div></aside></div>
      {selected&&<div className="fillAudit"><span>REFERENCE {Number(selected.reference_entry).toFixed(2)} → {Number(selected.reference_exit).toFixed(2)}</span><span>ACTUAL FILL {Number(selected.entry).toFixed(2)} → {Number(selected.exit).toFixed(2)}</span><span>GROSS {money(selected.gross_pnl)}</span><span className="cost">COSTS −{money(selected.total_costs)}</span><strong>NET {money(selected.net_pnl)}</strong></div>}
    </section>
    <section className="panel phase5Equity"><div className="panelTitle"><div><span>NET EQUITY</span><h2>Selected rule versus matched simple control</h2></div><small>Fixed-contract path · every series begins at $100,000</small></div><EquityChart series={[{name:candidate,color:"#43d69c",data:summary.equity??[]},{name:"First-candle control",color:"#6f7d8d",data:data.summaries?.[`${instrument}:BASE_CANDLE:${exit}:${sizing}`]?.equity??[]}]}/></section>
    <section className="phase5Lower"><article className="panel"><div className="panelTitle"><div><span>YEAR-BY-YEAR</span><h2>Net profit consistency</h2></div><small>{summary.positive_years??0} positive years</small></div><YearChart values={summary.by_year??{}}/></article><article className="panel phase5Delay"><div className="panelTitle"><div><span>MANUAL EXECUTION STRESS</span><h2>Does the signal survive delay?</h2></div></div><dl><div><dt>Original</dt><dd>{money(summary.net_profit??0)}</dd></div><div><dt>Enter 1 minute later</dt><dd>{money(summary.delay_stress?.one_minute?.net_profit??0)}</dd></div><div><dt>Enter 1 signal bar later</dt><dd>{money(summary.delay_stress?.one_signal_bar?.net_profit??0)}</dd></div><div><dt>After best 1% removed</dt><dd>{money(summary.tail?.net_after_best_1pct??0)}</dd></div></dl><p>A positive delay test is evidence of execution tolerance, not a guarantee that discretionary fills will match the simulation.</p></article></section>
    <section className="panel phase5Table"><div className="panelTitle"><div><span>CANDIDATE DISPOSITION</span><h2>Same frozen gates, no post-hoc rescue</h2></div><p>Negative control C17 is structurally barred from promotion.</p></div><div className="phase5Rows"><div className="phase5Row head"><span>RULE</span><span>NET · NQ 4R</span><span>VALIDATION</span><span>2024–25 EVAL</span><span>EVIDENCE</span></div>{compareIds.map(id=>{const item=data.summaries?.[`NQ:${id}:matched_4R:fixed1`]??{},decision=data.candidate_dispositions?.[id];return <button className={`phase5Row ${candidate===id?"active":""}`} key={id} onClick={()=>{setCandidate(id);setInstrument("NQ");setExit("matched_4R");setSizing("fixed1");setCost(1)}}><span><b>{id}</b><small>{PHASE5_NAMES[id]??id}</small></span><strong className={item.net_profit>=0?"profit":"loss"}>{money(item.net_profit??0)}</strong><span className={(item.periods?.validation?.net_profit??0)>=0?"profit":"loss"}>{money(item.periods?.validation?.net_profit??0)}</span><span className={(item.periods?.historical_evaluation?.net_profit??0)>=0?"profit":"loss"}>{money(item.periods?.historical_evaluation?.net_profit??0)}</span><em>{String(decision?.evidence??"control").replaceAll("_"," ")}</em></button>})}</div></section>
    <section className="phase5Plain"><div><span>GOOD / BAD DAY MODEL</span><strong>{data.good_bad_day?.conclusion??"Not available"}</strong><p>The regularized models failed to predict later-period outcomes reliably, so no day filter was promoted.</p></div><div><span>PRACTICAL CLASSIFICATION</span><strong>Historical artifact only</strong><p>The Phase 5 C01 execution is invalid. Corrected Phase 7 evidence does not authorize capital deployment.</p></div><div><span>FUTURE HOLDOUT</span><strong>Not justified</strong><p>Phase 7 found material exceptional-trade dependence. The protected 2026 market holdout remains unopened.</p></div></section>
    {advanced&&<section className="researchPanel panel phase5Research"><div className="panelTitle"><div><span>ADVANCED PHASE 5 RESEARCH</span><h2>Multiple testing, tail, and selection diagnostics</h2></div></div><div className="researchCards"><Research label="White reality check" value={`p ${data.inference?.white_reality_check_spa?.reality_check_p_value??"—"}`} note="Candidate family vs matched control"/><Research label="SPA-style max" value={`p ${data.inference?.white_reality_check_spa?.spa_p_value??"—"}`} note="Stationary bootstrap"/><Research label="PBO" value={String(data.inference?.pbo_cscv?.pbo??"—")} note="Combinatorially symmetric cross-validation"/><Research label="Honest trials" value={String(summary.deflated_sharpe?.trials??data.inference?.honest_configuration_count??"—")} note="Deflated Sharpe input"/><Research label="Best 5 / net" value={`${Number((summary.tail?.top5_share_net??0)*100).toFixed(1)}%`} note="Upper-tail dependence"/><Research label="Raw cache" value={data.raw_cache_immutable?"MATCH":"FAIL"} note="Before/after SHA-256"/></div><div className="phase5AuditGrid"><div><span>POST-SELECTION PARAMETER PLATEAU</span><h3>All 9 neighboring cells stayed profitable</h3><div className="plateauGrid">{Object.entries(data.robustness?.parameter_surface??{}).map(([key,item]:[string,any])=><article key={key} className={key==="ema_200:volume_1.0"?"center":""}><small>{key.replace("ema_","EMA ").replace(":volume_"," · VOL ")}</small><strong>{money(item.net_profit)}</strong><em>{item.positive_years}/8 positive years</em></article>)}</div><p>The center is the frozen EMA200 / 1.0-volume rule. The surface slopes toward looser settings, so none of these audit cells may replace it post hoc.</p></div><div><span>EXPANDING WALK-FORWARD</span><h3>Prior years selected C01 for every 2022–2025 test</h3><div className="walkRows">{(data.supplemental?.expanding_walk_forward??[]).map((row:any)=><div key={row.evaluation_year}><b>{row.evaluation_year}</b><strong className={row.evaluation_net_profit>=0?"profit":"loss"}>{money(row.evaluation_net_profit)}</strong><small>selected from prior years</small></div>)}</div><p>Supportive stability audit only. It cannot restore a clean holdout after all 2018–2025 observations were inspected.</p></div></div></section>}
  </>;
}

function Loading({error}:{error:string}){return <main className="loading"><div className="identity"><span className="logo">O/T</span><div><strong>OPEN / TEN</strong><small>Nasdaq futures strategy tester</small></div></div><h1>{error?"Start the local research API":"Loading corrected cached research…"}</h1><p>{error?"Run `npm run dev:api`, then refresh this page. No synthetic performance is substituted when the verified cache is unavailable.":"Reading the completed 2018–2025 backtest. 2026 remains untouched."}</p><div className="safetyText">NO LIVE TRADING · NO EDGE CLAIM IS PERMITTED WITHOUT HOLDOUT EVIDENCE</div></main>}
function Kpi({label,value,note,positive,bad}:{label:string;value:string;note:string;positive?:boolean;bad?:boolean}){return <article><span>{label}</span><strong className={positive?"profit":bad?"loss":""}>{value}</strong><small>{note}</small></article>}
function Research({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function ExitAuditCard({choice,title,item,selected}:{choice:string;title:string;item:any;selected:boolean}){const m=item.metrics,c=item.concentration.tests;return <article className={`exitCard ${selected?"selected":""}`}><header><div><span>OPTION {choice}</span><strong>{title}</strong></div>{selected&&<b>PAPER CANDIDATE</b>}</header><div className="exitStats"><div><span>NET PROFIT</span><strong className="profit">{money(m.net_profit)}</strong></div><div><span>PROFIT FACTOR</span><strong>{num(m.profit_factor,3)}</strong></div><div><span>MAX DRAWDOWN</span><strong className="loss">{pct(m.max_drawdown)}</strong></div><div><span>AVERAGE TRADE</span><strong>{money(m.average_trade)}</strong></div><div><span>MEDIAN TRADE</span><strong>{money(m.median_trade)}</strong></div><div><span>BREAK-EVEN COST</span><strong>{money(item.cost_break_even.break_even_all_in_round_trip_cost)}</strong></div></div><p>{m.trades.toLocaleString()} identical sessions · {(m.win_rate*100).toFixed(1)}% wins · {m.max_consecutive_losses} max consecutive losses · {(m.time_in_market.fraction_of_available_rth*100).toFixed(1)}% time in market · best five = {(c.best_5_trades.share_of_final_net_profit*100).toFixed(1)}% of net.</p></article>}
function ComparisonCard({title,subtitle,accent,metrics,core,selected,onSelect,costLevels}:{title:string;subtitle:string;accent:"simple"|"ema";metrics:any;core:any;selected:boolean;onSelect:()=>void;costLevels:any[]}){const cost=costLevels.filter(row=>[1,2,3,4].includes(row.multiplier));return <article className={`duelCard ${accent} ${selected?"selected":""}`}><div className="duelHead"><div><span>{accent==="simple"?"SIMPLER RULE":"EMA FILTER"}</span><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onSelect}>{selected?"VIEWING TRADES":"VIEW TRADES"}</button></div><div className="duelMetrics"><div><span>NET PROFIT</span><strong className="profit">{money(metrics.net_profit)}</strong></div><div><span>AVG / TRADE</span><strong>{money(metrics.average_trade)}</strong></div><div><span>MAX DRAWDOWN</span><strong className="loss">{pct(metrics.max_drawdown)}</strong></div><div><span>WIN RATE</span><strong>{(metrics.win_rate*100).toFixed(1)}%</strong></div><div><span>TRADES</span><strong>{metrics.trades.toLocaleString()}</strong></div><div><span>ALL EXECUTION COSTS</span><strong>{money(metrics.total_costs)}</strong></div></div><div className="yearRibbon">{Object.entries(metrics.by_year).map(([year,value]:any)=><div key={year} title={`${year}: ${money(value)}`}><i className={value>=0?"up":"down"} style={{height:`${Math.max(4,Math.min(28,4+Math.abs(value)/2500))}px`}}/><span>{String(year).slice(2)}</span></div>)}</div><div className="directionSplit"><div><span>LONG</span><b>{money(metrics.long.net_profit)}</b><small>{metrics.long.trades} trades</small></div><div><span>SHORT</span><b>{money(metrics.short.net_profit)}</b><small>{metrics.short.trades} trades</small></div><div><span>WORST STREAK</span><b>{metrics.max_consecutive_losses} losses</b><small>fixed one contract</small></div></div>{cost.length>0&&<div className="costRibbon"><span>COST STRESS</span>{cost.map(row=><div key={row.multiplier}><b>{row.multiplier}×</b><em className={row.net_profit>=0?"profit":"loss"}>{money(row.net_profit)}</em></div>)}</div>}<div className="duelFoot"><span>Profit factor {num(metrics.profit_factor,2)}</span><span>{metrics.positive_years}/{metrics.years} positive years</span><span>{money(core.total_costs)} exact costs</span></div></article>}
